### ISSUE TITLE
Add export of `FakeResponseType` and `PerftoolComponent`

### ISSUE THREAD

**Issue by saranchonkau** [salute-developers/perftool#471]
**Is your feature request related to a problem? Please describe.**
I'm trying to write perf test but TS throws error

```typescript
import { intercept } from '@salutejs/perftool';
// long non-standard import
import type { PerftoolComponent } from '@salutejs/perftool/dist/client/measurement/runner'; 

export const Default: PerftoolComponent = () => {
  return <div></div>;
};

Default.beforeTest = async () => {
  await intercept({
    method: 'GET',
    responseType: 'file', // TS2322: Type "file" is not assignable to type FakeResponseType | undefined
    source: '**/some.client.js',
    response: 'public/js/some.client.js',
  });
};
```
I tried to use `FakeResponseType` directly, but its value is not exported from the package...
I can write something like this, but it looks like workaround but not as intended.
```typescript
import type { FakeResponseType } from '@salutejs/perftool/dist/api/intercept';
...
await intercept({
    method: 'GET',
    responseType: 'file' as FakeResponseType.File,
    source: '**/some.client.js',
    response: 'public/js/some.client.js',
});
```

**Describe the solution you'd like**
Would be great if you add export of `FakeResponseType` object and type `PerftoolComponent`, so I will be able to just import them as usual:
```typescript
import { PerftoolComponent, FakeResponseType } from '@salutejs/perftool';
``` 

**Describe alternatives you've considered**
Or you may allow to pass common strings `'file' | 'json' | 'abort'` instead of `const enum`

**Comment by akhdrv** [comment]
Const enums were a bad idea, it's a known issue. Now string literals will be used instead
